// Auto-generated by Clean Language Compiler
// Target: browser
// WASM file: paddle-game.wasm

/**
 * CleanBridge - Runtime bridge for Clean Language WASM modules in browsers
 *
 * Provides implementations for:
 * - Console I/O (print, printl)
 * - User input (via window.prompt)
 * - File operations (via localStorage)
 * - HTTP operations (via fetch API)
 */
export class CleanBridge {
  constructor(memory) {
    this.memory = memory;
    this.decoder = new TextDecoder('utf-8');
    this.encoder = new TextEncoder();
  }

  /**
   * Read a Clean Language string from WASM memory
   * String format: [length: i32 (4 bytes)][data: bytes...]
   */
  readString(ptr) {
    if (ptr === 0) return '';
    const view = new DataView(this.memory.buffer);
    const length = view.getInt32(ptr, true); // little-endian
    if (length <= 0) return '';
    const bytes = new Uint8Array(this.memory.buffer, ptr + 4, length);
    return this.decoder.decode(bytes);
  }

  /**
   * Write a JavaScript string to WASM memory
   * Returns pointer to the new string
   */
  writeString(str, allocFn) {
    const bytes = this.encoder.encode(str);
    const ptr = allocFn(bytes.length + 4); // 4 bytes for length prefix
    const view = new DataView(this.memory.buffer);
    view.setInt32(ptr, bytes.length, true); // little-endian
    new Uint8Array(this.memory.buffer, ptr + 4, bytes.length).set(bytes);
    return ptr;
  }

  /**
   * Get the import object for WASM instantiation
   */
  getImports(allocFn) {
    const self = this;

    return {
      env: {
        // Console I/O
        print: (ptr) => {
          const text = self.readString(ptr);
          console.log(text);
        },

        printl: (ptr) => {
          const text = self.readString(ptr);
          console.log(text);
        },

        // User input (browser prompt)
        input: (promptPtr) => {
          const prompt = self.readString(promptPtr);
          const result = window.prompt(prompt) || '';
          return self.writeString(result, allocFn);
        },

        input_integer: (promptPtr) => {
          const prompt = self.readString(promptPtr);
          const result = window.prompt(prompt) || '0';
          return parseInt(result, 10) || 0;
        },

        input_float: (promptPtr) => {
          const prompt = self.readString(promptPtr);
          const result = window.prompt(prompt) || '0';
          return parseFloat(result) || 0.0;
        },

        input_yesno: (promptPtr) => {
          const prompt = self.readString(promptPtr);
          const result = window.prompt(prompt + ' (yes/no)') || 'no';
          return result.toLowerCase().startsWith('y') ? 1 : 0;
        },

        // File operations (localStorage-based)
        file_read: (pathPtr) => {
          const path = self.readString(pathPtr);
          const content = localStorage.getItem(`clean:${path}`);
          if (content === null) return 0;
          return self.writeString(content, allocFn);
        },

        file_write: (pathPtr, contentPtr) => {
          const path = self.readString(pathPtr);
          const content = self.readString(contentPtr);
          try {
            localStorage.setItem(`clean:${path}`, content);
            return 1;
          } catch (e) {
            console.error('File write error:', e);
            return 0;
          }
        },

        file_exists: (pathPtr) => {
          const path = self.readString(pathPtr);
          return localStorage.getItem(`clean:${path}`) !== null ? 1 : 0;
        },

        file_delete: (pathPtr) => {
          const path = self.readString(pathPtr);
          localStorage.removeItem(`clean:${path}`);
          return 1;
        },

        // HTTP operations (fetch-based)
        http_get: (urlPtr) => {
          // Note: This is synchronous for WASM compatibility
          // In practice, you may need async handling
          const url = self.readString(urlPtr);
          console.warn('http_get in browser is limited - consider async patterns');
          return 0; // Return empty for sync context
        },

        http_post: (urlPtr, bodyPtr) => {
          const url = self.readString(urlPtr);
          const body = self.readString(bodyPtr);
          console.warn('http_post in browser is limited - consider async patterns');
          return 0;
        },

        http_put: (urlPtr, bodyPtr) => {
          const url = self.readString(urlPtr);
          const body = self.readString(bodyPtr);
          console.warn('http_put in browser is limited - consider async patterns');
          return 0;
        },

        http_delete: (urlPtr) => {
          const url = self.readString(urlPtr);
          console.warn('http_delete in browser is limited - consider async patterns');
          return 0;
        },

        // Memory operations (if needed by runtime)
        memory_copy: (dest, src, len) => {
          const destArray = new Uint8Array(self.memory.buffer, dest, len);
          const srcArray = new Uint8Array(self.memory.buffer, src, len);
          destArray.set(srcArray);
        }
      }
    };
  }

  /**
   * Async HTTP methods for proper browser usage
   */
  async httpGet(url) {
    const response = await fetch(url);
    return await response.text();
  }

  async httpPost(url, body, contentType = 'application/json') {
    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': contentType },
      body: body
    });
    return await response.text();
  }

  async httpPut(url, body, contentType = 'application/json') {
    const response = await fetch(url, {
      method: 'PUT',
      headers: { 'Content-Type': contentType },
      body: body
    });
    return await response.text();
  }

  async httpDelete(url) {
    const response = await fetch(url, { method: 'DELETE' });
    return await response.text();
  }
}

export default CleanBridge;
