// Auto-generated by Clean Language Compiler
// Target: browser
// WASM file: paddle-game.wasm

import { CleanBridge } from './bridge.js';

/**
 * Load and run a Clean Language WASM module
 */
export async function loadCleanModule(wasmPath = './paddle-game.wasm') {
  // Fetch and compile the WASM module
  const response = await fetch(wasmPath);
  const wasmBytes = await response.arrayBuffer();

  // Create memory (1 page = 64KB, allow growth to 256 pages = 16MB)
  const memory = new WebAssembly.Memory({ initial: 1, maximum: 256 });

  // Create bridge
  const bridge = new CleanBridge(memory);

  // Track heap pointer for allocation
  let heapPtr = 1024; // HEAP_START

  function malloc(size) {
    // Align to 8 bytes
    const aligned = (heapPtr + 7) & ~7;
    heapPtr = aligned + size;
    return aligned;
  }

  // Get imports with allocator
  const imports = bridge.getImports(malloc);
  imports.env.memory = memory;

  // Instantiate the module
  const { instance } = await WebAssembly.instantiate(wasmBytes, imports);

  // Run the start function if it exists
  if (instance.exports._start) {
    instance.exports._start();
  } else if (instance.exports.start) {
    instance.exports.start();
  } else if (instance.exports.main) {
    instance.exports.main();
  }

  return {
    instance,
    memory,
    bridge,
    exports: instance.exports
  };
}

/**
 * Simple runner - loads and executes the WASM
 */
export async function run() {
  try {
    const module = await loadCleanModule();
    console.log('Clean Language module loaded successfully');
    return module;
  } catch (error) {
    console.error('Failed to load Clean Language module:', error);
    throw error;
  }
}

// Auto-run if this is the main module
if (typeof document !== 'undefined') {
  document.addEventListener('DOMContentLoaded', () => {
    run().catch(console.error);
  });
}

export default { loadCleanModule, run };
