/*!
 * Server-Side Rendering (SSR) Engine for Frame UI
 *
 * This module provides the SSR engine that executes component render() methods
 * in WASM and generates HTML for server-side rendering.
 *
 * ## Architecture
 *
 * 1. Component Discovery: Find and load component classes from WASM
 * 2. Component Instantiation: Create component instances with data
 * 3. Render Invocation: Call component's render() method
 * 4. HTML Generation: Get rendered HTML string from WASM
 * 5. Page Wrapping: Wrap in full HTML document
 *
 * ## Example Usage
 *
 * ```ignore
 * let ssr = SsrEngine::new(runtime);
 * let html = ssr.render_component("UserCard", json!({"user": {"name": "John"}})).await?;
 * ```
 */

use anyhow::{Context, Result};
use serde_json::Value;
use std::sync::Arc;

use crate::runtime::WasmRuntime;

/// Server-Side Rendering engine
pub struct SsrEngine {
    runtime: Arc<WasmRuntime>,
}

impl SsrEngine {
    /// Create a new SSR engine with the given WASM runtime
    pub fn new(runtime: Arc<WasmRuntime>) -> Self {
        Self { runtime }
    }

    /// Render a component to HTML
    ///
    /// This function:
    /// 1. Instantiates the component with the provided data
    /// 2. Calls the component's render() method
    /// 3. Returns the generated HTML string
    ///
    /// # Arguments
    ///
    /// * `component_name` - Name of the component class (e.g., "UserCard")
    /// * `data` - JSON data to pass to the component constructor
    ///
    /// # Returns
    ///
    /// HTML string generated by the component's render() method
    pub async fn render_component(&self, component_name: &str, data: Value) -> Result<String> {
        // Call the component's render function via WASM
        // The WASM module should export a function like: __render_UserCard(data)
        let render_fn = format!("__render_{}", component_name);

        let result = self.runtime.call_function(&render_fn, data)
            .await
            .context(format!("Failed to render component '{}'", component_name))?;

        // Extract HTML string from result
        if let Some(html) = result.as_str() {
            Ok(html.to_string())
        } else {
            Err(anyhow::anyhow!(
                "Component '{}' render() did not return a string",
                component_name
            ))
        }
    }

    /// Render a component and wrap it in a full HTML page
    ///
    /// This generates a complete HTML document with:
    /// - DOCTYPE declaration
    /// - HTML head with title and meta tags
    /// - Body with rendered component
    /// - Client-side hydration scripts (optional)
    ///
    /// # Arguments
    ///
    /// * `component_name` - Name of the component class
    /// * `data` - JSON data for the component
    /// * `page_title` - Title for the HTML page
    /// * `enable_hydration` - Whether to include client-side hydration
    ///
    /// # Returns
    ///
    /// Complete HTML document as a string
    pub async fn render_page(
        &self,
        component_name: &str,
        data: Value,
        page_title: &str,
        enable_hydration: bool,
    ) -> Result<String> {
        // Render the component
        let component_html = self.render_component(component_name, data.clone()).await?;

        // Build full HTML page
        let html = self.build_html_page(
            page_title,
            &component_html,
            enable_hydration,
            component_name,
            &data,
        );

        Ok(html)
    }

    /// Build a complete HTML page
    fn build_html_page(
        &self,
        title: &str,
        body_content: &str,
        enable_hydration: bool,
        component_name: &str,
        data: &Value,
    ) -> String {
        let hydration_script = if enable_hydration {
            // Include hydration data and script
            format!(
                r#"<script id="__FRAME_DATA__" type="application/json">
    {{"component": "{}", "data": {}}}
</script>
<script src="/js/frame-hydrate.js"></script>"#,
                component_name,
                serde_json::to_string(data).unwrap_or_else(|_| "{}".to_string())
            )
        } else {
            String::new()
        };

        format!(
            r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{}</title>
    <link rel="stylesheet" href="/css/frame.css">
</head>
<body>
{}
{}
</body>
</html>"#,
            title, body_content, hydration_script
        )
    }

    /// Render multiple components on a page
    ///
    /// This allows composing a page from multiple components.
    ///
    /// # Arguments
    ///
    /// * `components` - List of (component_name, data) tuples
    /// * `page_title` - Title for the page
    ///
    /// # Returns
    ///
    /// Complete HTML document with all components rendered
    pub async fn render_multi_component_page(
        &self,
        components: Vec<(&str, Value)>,
        page_title: &str,
    ) -> Result<String> {
        let mut rendered_components = Vec::new();

        // Render each component
        for (name, data) in components {
            let html = self.render_component(name, data).await?;
            rendered_components.push(html);
        }

        // Combine all components
        let body_content = rendered_components.join("\n");

        // Build full page without hydration (multi-component hydration is more complex)
        let html = self.build_html_page(page_title, &body_content, false, "", &Value::Null);

        Ok(html)
    }
}

/// Configuration for SSR rendering
#[derive(Debug, Clone)]
pub struct SsrConfig {
    /// Enable client-side hydration
    pub enable_hydration: bool,
    /// Default page title
    pub default_title: String,
    /// Path to CSS stylesheet
    pub css_path: String,
    /// Path to hydration JavaScript
    pub js_path: String,
}

impl Default for SsrConfig {
    fn default() -> Self {
        Self {
            enable_hydration: true,
            default_title: "Frame App".to_string(),
            css_path: "/css/frame.css".to_string(),
            js_path: "/js/frame-hydrate.js".to_string(),
        }
    }
}

impl SsrConfig {
    /// Create a new SSR config
    pub fn new() -> Self {
        Self::default()
    }

    /// Disable client-side hydration
    pub fn without_hydration(mut self) -> Self {
        self.enable_hydration = false;
        self
    }

    /// Set default page title
    pub fn with_title(mut self, title: impl Into<String>) -> Self {
        self.default_title = title.into();
        self
    }

    /// Set CSS path
    pub fn with_css(mut self, path: impl Into<String>) -> Self {
        self.css_path = path.into();
        self
    }

    /// Set JavaScript path
    pub fn with_js(mut self, path: impl Into<String>) -> Self {
        self.js_path = path.into();
        self
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_ssr_config_default() {
        let config = SsrConfig::default();
        assert!(config.enable_hydration);
        assert_eq!(config.default_title, "Frame App");
        assert_eq!(config.css_path, "/css/frame.css");
    }

    #[test]
    fn test_ssr_config_builder() {
        let config = SsrConfig::new()
            .without_hydration()
            .with_title("My App")
            .with_css("/styles/main.css");

        assert!(!config.enable_hydration);
        assert_eq!(config.default_title, "My App");
        assert_eq!(config.css_path, "/styles/main.css");
    }

    // Note: Tests that create SsrEngine require a valid WASM file
    // These tests verify the HTML generation logic only

    #[test]
    fn test_html_page_structure() {
        // Test HTML generation without creating a runtime
        let title = "Test Page";
        let body = "<div>Content</div>";

        // Manually build HTML to test structure
        let html = format!(
            r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{}</title>
    <link rel="stylesheet" href="/css/frame.css">
</head>
<body>
{}

</body>
</html>"#,
            title, body
        );

        assert!(html.contains("<!DOCTYPE html>"));
        assert!(html.contains("<title>Test Page</title>"));
        assert!(html.contains("<div>Content</div>"));
    }

    #[test]
    fn test_hydration_data_format() {
        // Test hydration script generation
        let component_name = "UserCard";
        let data = serde_json::json!({"user": "John"});

        let hydration_script = format!(
            r#"<script id="__FRAME_DATA__" type="application/json">
    {{"component": "{}", "data": {}}}
</script>
<script src="/js/frame-hydrate.js"></script>"#,
            component_name,
            serde_json::to_string(&data).unwrap()
        );

        assert!(hydration_script.contains("__FRAME_DATA__"));
        assert!(hydration_script.contains("UserCard"));
        assert!(hydration_script.contains("John"));
        assert!(hydration_script.contains("frame-hydrate.js"));
    }
}
